 <h1 style="color: blue; font-weight: bold; font-size: 36px;"> Numpy in Python </h1>


## One Dimensional Numpy

NumPy (short for Numerical Python) is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures. NumPy is widely used in various fields such as data analysis, machine learning, and scientific research due to its powerful capabilities and ease of use.

In [3]:
import numpy as np 

In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

###Type

In [ ]:
# Check the type of the array

type(a)

In [ ]:
# Check the type of the values stored in numpy array

a.dtype

We can change the value of the array.

In [4]:
c = np.array([20, 1, 2, 3, 4])
c


array([20,  1,  2,  3,  4])

In [ ]:
c[0] = 100 # change the first element of the array to 100
c

In [ ]:
# Assign the 5th element to 0

c[4] = 0
c

In [5]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [6]:
#define the steps in slicing, like this: [start:end:step].
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [7]:
print(arr[:4])

[1 2 3 4]


**Other Attributes**

In [ ]:
a = np.array([0, 1, 2, 3, 4])
a

In [ ]:
# Get the size of numpy array

a.size

In [ ]:
# Get the number of dimensions of numpy array

a.ndim

In [ ]:
# Get the shape/size of numpy array

a.shape

***Numpy Statistical Functions***


In [ ]:
# Create a numpy array

a = np.array([1, -1, 4, 7])

In [ ]:
# Get the mean of numpy array

mean = a.mean()
mean

In [ ]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

In [ ]:
# Get the biggest value in the numpy array

max_a = a.max()
max_a

In [ ]:
# Get the smallest value in the numpy array

min_a = a.min()
min_a

## Two Dimensional Numpy

In [ ]:
# Create a list
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

In [ ]:
# Convert list to Numpy Array

A = np.array(a)
A

In [ ]:
# Show the numpy array dimensions

A.ndim

In [ ]:
# Show the numpy array shape

A.shape

In [ ]:
# Access the element on the second row and third column
A[1, 2]

In [ ]:
A[1][2]

In [ ]:
# Access the element on the first row and first and second columns

A[0][0:2]

In [ ]:
# Access the element on the first and second rows and third column

A[0:2, 2]

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

In [ ]:
# Add X and Y

Z = X + Y
Z

In [ ]:
# Multiply Y with 2

Z = 2 * Y

In [ ]:
# Multiply X with Y# Calculate the sine of Z

np.sin(Z)

Z = X * Y
Z# Calculate the sine of Z

np.sin(Z)